import Head from "next/head";
import { ReactElement } from "react";
import { APP_NAME } from "../../config/app";
import Header from "../global/Header";

type Props = { children: ReactElement };

function RootLayout({ children }: Props) {
  return (
    <>
      <Head>
        <title>{APP_NAME}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main>{children}</main>
    </>
  );
}

export default RootLayout;
